name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  build_wheels:
    name: Build wheels on ${{ matrix.os }} for ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python: [ 'cp39-*', 'cp310-*', 'cp311-*', 'cp312-*', 'cp313-*' ]
    steps:
      - uses: actions/checkout@v4

      - name: Install ninja-build
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install CUDA
        if: runner.os == 'Linux' || runner.os == 'Windows'
        uses: Jimver/cuda-toolkit@v0.2.23
        id: cuda-toolkit
        with:
          cuda: '12.8.1'
          sub-packages: ${{ runner.os == 'Linux' && '["nvcc", "cudart-dev"]' || '["nvcc", "cudart", "thrust", "libcublas_dev", "libcurand_dev", "libcusolver_dev", "libcusparse_dev"]' }}
          non-cuda-sub-packages: ${{ runner.os == 'Linux' && '["libcublas-dev", "libcurand-dev", "libcusolver-dev", "libcusparse-dev"]' || '[]' }}
          method: 'network'

      - name: Build wheels
        env:
          CIBW_BUILD: ${{ matrix.python }}
        uses: pypa/cibuildwheel@v2.23.3

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  publish_on_pypi:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: [ build_sdist, build_wheels ]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - name: Publish wheels to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
