name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build sdist
        run: pipx run build --sdist

      - name: Upload sdist
        uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

  build_wheels:
    name: Build wheels on ${{ matrix.os }} for ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python: [ 'cp39-*', 'cp310-*', 'cp311-*', 'cp312-*', 'cp313-*' ]
        exclude:  # TODO: torch>=2.5.0 is currently not available for Windows and Mac
          - os: windows-latest
            python: 'cp313-*'
          - os: macos-latest
            python: 'cp313-*'
    steps:
      - uses: actions/checkout@v3

      - name: Install ninja-build
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Build wheels
        env:
          CIBW_BUILD: ${{ matrix.python }}
        uses: pypa/cibuildwheel@v2.22.0

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  publish_on_pypi:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: [ build_sdist, build_wheels ]
    runs-on: ubuntu-latest
    steps:
      - name: Download wheels
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - name: Publish wheels to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
